# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import acquired_pb2 as acquired__pb2


class AcquiredStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.get_campaigns = channel.unary_stream(
        '/Acquired/get_campaigns',
        request_serializer=acquired__pb2.GetCampaignsRequest.SerializeToString,
        response_deserializer=acquired__pb2.Campaign.FromString,
        )


class AcquiredServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def get_campaigns(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AcquiredServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'get_campaigns': grpc.unary_stream_rpc_method_handler(
          servicer.get_campaigns,
          request_deserializer=acquired__pb2.GetCampaignsRequest.FromString,
          response_serializer=acquired__pb2.Campaign.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Acquired', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
